### ISSUE TITLE
gnome-mplayer fail to build with libgpod-dev 0.8.2-3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wolfv/gnome-mplayer#564]
```
Build log:
http://people.debian.org/~lucas/logs/2011/09/23/gnome-mplayer_1.0.4-1_lsid64.bui
ldlog

Failing reason:
support.h:46:23: fatal error: gpod/itdb.h: No such file or directory

Tail of logs:
make[4]: Entering directory 
`/build/gnome-mplayer-lWoZEh/gnome-mplayer-1.0.4/src'
  CC     gui.o
In file included from gui.c:30:0:
support.h:46:23: fatal error: gpod/itdb.h: No such file or directory
compilation terminated.
make[4]: *** [gui.o] Error 1
make[4]: Leaving directory `/build/gnome-mplayer-lWoZEh/gnome-mplayer-1.0.4/src'
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory `/build/gnome-mplayer-lWoZEh/gnome-mplayer-1.0.4/src'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/build/gnome-mplayer-lWoZEh/gnome-mplayer-1.0.4'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/build/gnome-mplayer-lWoZEh/gnome-mplayer-1.0.4'
make: *** [build-stamp] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

New libgpod: http://packages.debian.org/source/sid/libgpod
```

Original issue reported on code.google.com by `happyaro...@gmail.com` on 26 Sep 2011 at 1:54
